### ISSUE TITLE
Reduce editItem() method's complexity

### ISSUE THREAD

**Issue by LavishSwarnkar** [imAtulSharma/MyEcomConsole#4]
https://github.com/imAtulSharma/MyEcom/blob/e0d2edf2e7bb5837475f68db3d8fb5e5cc06b804/src/com/streamliners/models/CartOperations.java#L146

While editing a product in cart, what is the need of getting the product from products hashmap?

Just edit the quantity from cart.

Use the key "ProductName VariantName" to get the item and edit it's quantity directly.

**Comment by imAtulSharma** [comment]
Actually in the cart I have used different pattern for the key naming of the product that's why need the specific product from the hash map to know which product is to edit.

Can't edit the quantity directly from the cart as there is only function for the increment of the quantity of the particular weight.
But I didn't show the two variants of the same product in different way. I just want to completely change the variant of the product with new quantity.
